# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.4
clone:
  depth: full
pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm install -g gulp-cli
          - gulp lint
  branches:
    development:
      - step:
          caches:
            - node
          script:
            - npm install
            - npm install -g gulp-cli
            - gulp lint
            - git config --global user.email "admin@proliteracy.ca"
            - git config --global user.name "Alfred Yang"
            - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_STAG_NAME.git development:master